---
title:    | 
 | Visualización de datos COVID-Chilevisión
 |
 | TranslucidData & OneMind-DataScience
author:    | 
 | **Antonio Canepa, Ph.D.**
 | *[www.onemind-datascience.com](https://www.onemind-datascience.com/)*
 |
 | **Mauricio Cifuentes, Ph.D.**
 | *[transluciddata.com](https://transluciddata.com/)*

date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
    toc_depth: 6
  pdf_document:
    toc: yes
---
```{r echo=FALSE}
htmltools::img(src = knitr::image_uri(f = "INPUT_Files/OMDS/OMDS_Logo_small.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
```


# Este documento es para ver una wea
La weá o figura más mulamente dibujada

### Los datos serían estos:

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
Data_Fatalidad <- tibble::tibble(Date = rep(seq(ymd('2020-05-09'),ymd('2020-05-15'), by = '1 day'), times = 2),
                       Numbers = c(304, 313, 323, 335, 346, 368, 394, 10, 9, 11, 12, 11, 22, 26),
                       Category = rep(c("Número de Muertos Acumulados", "Número de Muertos por día"), each = 7))
```

```{r echo=FALSE}
Data_Fatalidad
```

### La figura Original mostrada en Chilevisión
```{r echo=FALSE, fig.width= 8, fig.align = 'center'}
htmltools::img(src = knitr::image_uri(f = "INPUT_Files/original_image_chilevision.jpeg"))
```



### La figura como de verdad debería lucir

```{r echo=FALSE}
ggplot(Data_Fatalidad, aes(x = Date, y = Numbers)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = Category)) +
  geom_text(
    aes(x = Date, y = Numbers, label = Numbers, group = Category),
    position = position_dodge(width = 1),
    vjust = -0.5, size = 3.5
  ) +
  scale_x_date(breaks = seq(ymd('2020-05-09'),ymd('2020-05-15'), by = '1 day'),
               date_labels = "%d %B") +
  theme_bw() +
  lims(y = c(0, 410)) +
  labs(x = "", y = "", fill = "") +
  theme(strip.text.x = element_text(size = 10, colour = "black", angle = 90),
        strip.text.y = element_text(size = 12, colour = "black", angle = 0),
        axis.text.x = element_text(angle = 40, hjust = 1, vjust = 0.9),
        legend.position = "top")
```
